#!/bin/bash


# Initialize empty arrays
NUMBERS=()
STRINGS=()
NAMES=()

NUMBERS+=(1)
NUMBERS+=(2)
NUMBERS+=(3)

STRINGS+=("hello")
STRINGS+=("world")

NAMES+=("John")
NAMES+=("Eric")
NAMES+=("Jessica")


NumberOfNames=${#NAMES[@]}

second_name=${NAMES[1]}

echo "NUMBERS array: ${NUMBERS[@]}"
echo "STRINGS array: ${STRINGS[@]}"
echo "The number of names listed in the NAMES array: $NumberOfNames"
echo "The second name on the NAMES list is: $second_name"
